name: py37
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.20.3
  - pandas=1.3.5
  - networkx=2.5
  - matplotlib
  - optlang=1.4.4
  - bokeh=2.2.3
  - tqdm=4.56.0
  - pytest=4.6.11
  - statsmodels=0.12.1
  - sympy=1.6.1
  - pip
  - pip:
      - cobra==0.20.0
      - pytfa==0.9.3
      - scipy==1.6.3
